### PR TITLE
Restructure Google Cloud Audit Logs E2E test suite

### LINKED ISSUE #377: Cloud Audit Logs E2E test asserts for single event, but might receive any number of events
The E2E test suite for the Google Cloud Audit Logs source asserts for a single event:

```go
// test/e2e/sources/googlecloudrepositories/main.go
Expect(receivedEvents).To(HaveLen(1))
```

This is incorrect in this context, because Audit Logs collects events for _the whole Google Cloud project_, not just the resources created by the test. It is very likely that another test / application/ developer ends up generating unrelated Pub/Sub audit logs during the lifecycle of this test.

For this reason, we often observe [failures in E2E tests](https://github.com/triggermesh/triggermesh/actions/runs/1631370315/attempts/1).

### PR DESCRIPTION
**Pull request by antoineco**
- Rename a few variables for consistency with other Google Cloud tests
- Don't enforce that we receive a single event (see #377)
- Add test cases to assert that Kubernetes properly rejects objects with invalid or missing attributes

Fixes #377

### CODE REVIEW

File: test/e2e/sources/googlecloudauditlogs/main.go [hunk 1]
```diff
@@ -135,7 +140,6 @@ var _ = Describe("Google Cloud AuditLogs source", func() {
 				readReceivedEvents := readReceivedEvents(f.KubeClient, ns, sink.Ref.Name, &receivedEvents)
 
 				Eventually(readReceivedEvents, receiveTimeout, pollInterval).ShouldNot(BeEmpty())
-				Expect(receivedEvents).To(HaveLen(1))
```
Comment (cab105) [inline test/e2e/sources/googlecloudauditlogs/main.go:138]: Wouldn't it be better to expect there to be at least one event received otherwise the test will panic in the next line attempting to obtain the first element of a zero length array?

**Review by cab105 — COMMENTED** [review]
Sadly found one not-so minor nit, but should be an easy fix.

File: test/e2e/sources/googlecloudauditlogs/main.go (hunk 1 above)
Comment (antoineco) [reply test/e2e/sources/googlecloudauditlogs/main.go:138]: That case is covered by `ShouldNot(BeEmpty())` above. We won't reach that point if no event is received.

Comment (cab105) [reply test/e2e/sources/googlecloudauditlogs/main.go:138]: Oh right. I was expecting a `> 0` check here, but that works too.

**Review by cab105 — APPROVED** [review]
